/*
 * My awful Redis
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package main

import (
	"log"
	"net/http"
)

func main() {
	storage := NewAwfulRedisStorage()

	handler := NewAwfulRedisHandler(storage)

	log.Println("starting server at :8082")
	http.ListenAndServe(":8082", handler)
}
